// progress.vue
<template>
    <div id="progress">
        <div class="container">
            <div class="tile">
                <Timeline id="0"></Timeline>
                <Heatmap id="0"></Heatmap>
            </div>
        </div>
    </div>
</template>

<script>
import Timeline from "./timeline/timeline.vue";
import Heatmap from "./heatmap/heatmap.vue";

export default {
    components: {
        Heatmap,
        Timeline
    },
    data() {
        return {};
    }
}
</script>

<style lang="scss">
</style>

// js/progress/progress.jsx
import React from "react";
import { Grid } from "@material-ui/core";
import Timeline from "./timeline/timeline";
import Heatmap from "./heatmap/heatmap";
import ProgressBanner from "./banner";

export default class Progress extends React.Component {
  render() {
    return (
      <Grid container>
        <Grid item xs="12">
          <ProgressBanner />
        </Grid>
        <Grid item xs="12" md="6">
          <Timeline />
        </Grid>
        <Grid item xs="12" md="6">
          <Heatmap />
        </Grid>
      </Grid>
    );
  }
}
